name: Linux

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Addon version'
        required: true
        default: "6.0"

run-name: Building GDE GoZen - Linux - ${{ inputs.version }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Installing dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git bash yasm python3 python3-pip scons build-essential diffutils make wget unzip tar ffmpeg binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compiling FFmpeg arm64
        run: python3 -c 'import build; build.compile_ffmpeg("linux", "arm64")'
      - name: Build Linux debug arm64
        run: scons -j4 target=template_debug platform=linux arch=arm64
      - name: Build Linux release arm64
        run: scons -j4 target=template_release platform=linux arch=arm64

      - name: Clean scons
        run: scons --clean

      - name: Compiling FFmpeg x86_64
        run: python3 -c 'import build; build.compile_ffmpeg("linux", "x86_64")'
      - name: Build Linux debug x86_64
        run: scons -j4 target=template_debug platform=linux arch=x86_64
      - name: Build Linux release x86_64
        run: scons -j4 target=template_release platform=linux arch=x86_64

      - name: Upload addon
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen_linux_v${{ inputs.version }}
          path: test_room/addons/
          retention-days: 5

      - name: Upload test_room
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen_test_room_linux_v${{ inputs.version }}
          path: test_room/
          retention-days: 5

