name: Linux
run-name: Building GDE GoZen - Linux
on: 
  workflow_dispatch:
    inputs:
      artifact_addon:
        description: 'Get artifacts'
        required: true
        default: false
        type: boolean
      artifact_test_room:
        description: 'Get test_room'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Installing dependencies
        run: pacman -Syu --noconfirm git bash yasm python python-pip scons gcc diffutils make wget unzip tar ffmpeg
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Linux debug
        run: scons -j4 target=template_debug platform=linux arch=x86_64 use_system=no dev_build=yes
      - name: Build Linux release
        run: scons -j4 target=template_release platform=linux arch=x86_64 use_system=no recompile_ffmpeg=no

      - name: Uploading addon build
        if: ${{ github.event.inputs.artifact_addon == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: Addon_GDE_GoZen_Linux
          path: test_room/addons/
          retention-days: 5

      - name: Uploading test room build
        if: ${{ github.event.inputs.artifact_test_room == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: Test_room_GDE_GoZen_Linux
          path: test_room/
          retention-days: 5

