name: MacOS

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Addon version'
        required: true
        default: "6.0"

run-name: Building GDE GoZen - MacOS - ${{ inputs.version }}

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Installing dependencies
        run: |
          brew update
          brew install yasm scons diffutils make unzip ffmpeg
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compiling FFmpeg arm64
        run: python -c 'import sys; sys.path.append("."); import build; build.compile_ffmpeg_macos("arm64")'

      - name: Build MacOS debug arm64
        run: scons -j4 target=template_debug platform=macos arch=arm64
      - name: Build MacOS release arm64
        run: scons -j4 target=template_release platform=macos arch=arm64

      - name: Correct MacOS Binary paths
        run: python -c 'import sys; sys.path.append("."); import build; build.macos_fix("arm64")'

      - name: Upload addon
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen_macos_v${{ inputs.version }}
          path: test_room/addons/
          retention-days: 5

      - name: Upload test_room
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen_test_room_macos_v${{ inputs.version }}
          path: test_room/
          retention-days: 5

