name: MacOS
run-name: Building GDE GoZen - MacOS
on: 
  workflow_dispatch:
    inputs:
      artifact_addon:
        description: 'Get artifacts'
        required: true
        default: false
        type: boolean
      artifact_test_room:
        description: 'Get test_room'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Installing dependencies
        run: |
          brew update
          brew install yasm scons diffutils make unzip ffmpeg
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build FFmpeg
        run: ./ffmpeg.sh 3 1
      - name: Build MacOS debug
        run: scons -j4 target=template_debug platform=macos arch=arm64 dev_build=yes
      - name: Build MacOS release
        run: scons -j4 target=template_release platform=macos arch=arm64

      #- name: Correct MacOS Binary paths
      #  run: |
      #    python macos_rpath_fix.py
      #    otool -L bin/macos/debug/libgozen.macos.template_debug.dev.arm64.dylib
      #    otool -L bin/macos/release/libgozen.macos.template_release.arm64.dylib

      - name: Uploading addon build
        if: ${{ github.event.inputs.artifact_addon == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: Addon_GDE_GoZen_MacOS
          path: test_room/addons/
          retention-days: 5

      - name: Uploading test room build
        if: ${{ github.event.inputs.artifact_test_room == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: Test_room_GDE_GoZen_MacOS
          path: test_room/
          retention-days: 5

