name: Windows
run-name: Building GDE GoZen - Windows
on: 
  workflow_dispatch:
    inputs:
      artifact_addon:
        description: 'Get artifacts'
        required: true
        default: false
        type: boolean
      artifact_test_room:
        description: 'Get test_room'
        required: true
        default: false
        type: boolean
      artifact_addon_gpl:
        description: 'Get artifacts GPL'
        required: true
        default: false
        type: boolean
      artifact_test_room_gpl:
        description: 'Get test_room GPL'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Installing dependencies
        run: pacman -Syu --noconfirm git bash yasm python python-pip scons gcc diffutils make wget unzip tar mingw-w64 ffmpeg

      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore cached windows_debug
        id: cache-windows-debug-restore
        uses: actions/cache/restore@v4
        with:
          path: .scons-cache/
          key: windows_debug_addon
      - name: Build Windows debug
        run: scons -j4 target=template_debug platform=windows arch=x86_64 dev_build=yes recompile_ffmpeg=yes
      - name: Save cache windows_debug
        id: cache-windows-debug-save
        uses: actions/cache/save@v4
        with:
          path: .scons-cache/
          key: ${{ steps.cache-windows-debug-restore.outputs.cache-primary-key }}

      - name: Restore cached windows_release
        id: cache-windows-release-restore
        uses: actions/cache/restore@v4
        with:
          path: .scons-cache/
          key: windows_release_addon
      - name: Build Windows release
        run: scons -j4 target=template_release platform=windows arch=x86_64 recompile_ffmpeg=no
      - name: Save cache windows_release
        id: cache-windows-release-save
        uses: actions/cache/save@v4
        with:
          path: .scons-cache/
          key: ${{ steps.cache-windows-release-restore.outputs.cache-primary-key }}

      - name: Copying libs
        run: |
          cp -r bin/* test_room/addons/gde_gozen/bin/
          cp LICENSE test_room/addons/gde_gozen/

      - name: Uploading addon build
        if: ${{ github.event.inputs.artifact_addon == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: Addon_GDE_GoZen_Windows
          path: test_room/addons/
          retention-days: 1

      - name: Uploading test room build
        if: ${{ github.event.inputs.artifact_test_room == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: Test_room_GDE_GoZen_Windows
          path: test_room/
          retention-days: 1

  build-gpl:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Installing dependencies
        run: pacman -Syu --noconfirm git bash yasm python python-pip scons gcc diffutils make wget unzip tar mingw-w64 ffmpeg

      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore cached windows_debug
        id: cache-windows-debug-restore
        uses: actions/cache/restore@v4
        with:
          path: .scons-cache/
          key: windows_debug_addon
      - name: Build Windows debug
        run: scons -j4 target=template_debug platform=windows arch=x86_64 dev_build=yes recompile_ffmpeg=yes enable_gpl=yes
      - name: Save cache windows_debug
        id: cache-windows-debug-save
        uses: actions/cache/save@v4
        with:
          path: .scons-cache/
          key: ${{ steps.cache-windows-debug-restore.outputs.cache-primary-key }}

      - name: Restore cached windows_release
        id: cache-windows-release-restore
        uses: actions/cache/restore@v4
        with:
          path: .scons-cache/
          key: windows_release_addon
      - name: Build Windows release
        run: scons -j4 target=template_release platform=windows arch=x86_64 recompile_ffmpeg=no enable_gpl=yes
      - name: Save cache windows_release
        id: cache-windows-release-save
        uses: actions/cache/save@v4
        with:
          path: .scons-cache/
          key: ${{ steps.cache-windows-release-restore.outputs.cache-primary-key }}

      - name: Copying libs
        run: |
          cp -r bin/* test_room/addons/gde_gozen/bin/
          cp LICENSE.GPL3 test_room/addons/gde_gozen/

      - name: Uploading addon build
        if: ${{ github.event.inputs.artifact_addon_gpl == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: Addon_GDE_GoZen_Windows_GPL
          path: test_room/addons/
          retention-days: 1

      - name: Uploading test room build
        if: ${{ github.event.inputs.artifact_test_room_gpl == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: Test_room_GDE_GoZen_Windows_GPL
          path: test_room/
          retention-days: 1

