name: Windows
run-name: Building GDE GoZen - Windows
on: 
  workflow_dispatch:
    inputs:
      artifact_addon:
        description: 'Get addon'
        required: true
        default: false
        type: boolean
      artifact_test_room:
        description: 'Get test_room'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Installing dependencies
        run: pacman -Syu --noconfirm git bash yasm python python-pip scons gcc diffutils make wget unzip tar mingw-w64 ffmpeg
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Windows debug
        run: scons -j4 target=template_debug platform=windows arch=x86_64 dev_build=yes recompile_ffmpeg=yes
      - name: Build Windows release
        run: scons -j4 target=template_release platform=windows arch=x86_64 recompile_ffmpeg=no

      - name: Uploading addon build
        if: ${{ github.event.inputs.artifact_addon == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: Addon_GDE_GoZen_Windows
          path: test_room/addons/
          retention-days: 5

      - name: Uploading test room build
        if: ${{ github.event.inputs.artifact_test_room == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: Test_room_GDE_GoZen_Windows
          path: test_room/
          retention-days: 5

