name: Check Linux full build
run-name: Check build for Linux + FFmpeg
on:
  workflow_dispatch:
    inputs:
      artifact:
        description: 'Get artifacts'
        required: true
        default: false
        type: boolean

jobs:
  linux-build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Installing dependencies
        run: pacman -Syu --noconfirm ffmpeg git bash yasm python python-pip scons gcc diffutils make

      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore cached linux_full_debug
        id: cache-linux-full-debug-restore
        uses: actions/cache/restore@v4
        with:
          path: .scons-cache/
          key: linux_full_debug
      - name: Build Linux full debug
        run: scons -j4 target=template_debug platform=linux arch=x86_64 use_system=no dev_build=yes
      - name: Save cache linux_full_debug
        id: cache-linux-full-debug-save
        uses: actions/cache/save@v4
        with:
          path: .scons-cache/
          key: ${{ steps.cache-linux-full-debug-restore.outputs.cache-primary-key }}

      - name: Restore cached linux_full_release
        id: cache-linux-full-release-restore
        uses: actions/cache/restore@v4
        with:
          path: .scons-cache/
          key: linux_full_release
      - name: Build Linux full release
        run: scons -j4 target=template_release platform=linux arch=x86_64 use_system=no recompile_ffmpeg=no
      - name: Save cache linux_full_release
        id: cache-linux-full-release-save
        uses: actions/cache/save@v4
        with:
          path: .scons-cache/
          key: ${{ steps.cache-linux-full-release-restore.outputs.cache-primary-key }}

      - name: Uploading GDExtension artifact full release
        if: ${{ github.event.inputs.artifact == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen_linux_full_build
          path: bin/linux_full/
          retention-days: 1
          
