name: Check Linux build
run-name: Check build for Linux
on: 
  workflow_dispatch:
    inputs:
      artifact:
        description: 'Get artifacts'
        required: true
        default: false
        type: boolean

jobs:
  linux-build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Installing dependencies
        run: pacman -Syu --noconfirm ffmpeg git bash yasm python python-pip scons gcc diffutils make
    
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore cached linux_debug
        id: cache-linux-debug-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .cache
            godot_cpp
            ffmpeg
          key: linux_debug
      - name: Build Linux debug
        run: scons -j4 target=template_debug platform=linux arch=x86_64 use_system=yes dev_build=yes
      - name: Save cache linux_debug
        id: cache-linux-debug-save
        uses: actions/cache/save@v4
        with:
          path: |
            .cache
            godot_cpp
            ffmpeg
          key: ${{ steps.cache-linux-debug-restore.outputs.cache-primary-key }}

      - name: Restore cached linux_release
        id: cache-linux-release-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .cache
            godot_cpp
            ffmpeg
          key: linux_release
      - name: Build Linux release
        run: scons -j4 target=template_release platform=linux arch=x86_64 use_system=yes
      - name: Save cache linux_release
        id: cache-linux-release-save
        uses: actions/cache/save@v4
        with:
          path: |
            .cache
            godot_cpp
            ffmpeg
          key: ${{ steps.cache-linux-release-restore.outputs.cache-primary-key }}

      - name: Uploading GDExtension artifact release
        if: ${{ github.event.inputs.artifact == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen_linux_build
          path: bin/linux/
