name: Check Linux full build
run-name: Check build for Linux + FFmpeg
on:
  workflow_dispatch:
    inputs:
      artifact:
        description: 'Get artifacts'
        required: true
        default: false
        type: boolean

jobs:
  linux-build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Installing dependencies
        run: pacman -Syu --noconfirm ffmpeg git bash yasm python python-pip scons gcc diffutils make

      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Linux full Debug
        run: scons -j4 target=template_debug platform=linux arch=x86_64 use_system=no dev_build=yes
      - name: Build Linux full Release
        run: scons -j4 target=template_release platform=linux arch=x86_64 use_system=no

      - name: Uploading GDExtension artifact full release
        if: ${{ github.event.inputs.artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen_linux_full_build
          path: bin/linux_full/
          retention-days: 1
          
