name: Check Linux build
run-name: Check build for Linux
on: 
  workflow_dispatch:
    inputs:
      artifact:
        description: 'Get artifacts'
        required: true
        default: false
        type: boolean

jobs:
  linux-build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Installing dependencies
        run: pacman -Syu --noconfirm ffmpeg git bash yasm python python-pip scons gcc diffutils make
    
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Linux Debug
        run: scons -j4 target=template_debug platform=linux arch=x86_64 use_system=yes dev_build=yes
      - name: Build Linux Release
        run: scons -j4 target=template_release platform=linux arch=x86_64 use_system=yes

      - name: Uploading GDExtension artifact release
        if: ${{ github.event.inputs.artifact == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen_linux_build
          path: bin/linux/
