name: 1 | Linux

on: 
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'Addon version'
        required: true
        default: "6.0"

run-name: Linux build - ${{ inputs.version }}

jobs:
  build-x86_64:
    runs-on: ubuntu-22.04
    steps:
      - name: Installing dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git bash yasm python3 python3-pip scons build-essential diffutils make wget unzip tar ffmpeg binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libaom-dev

      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compiling FFmpeg x86_64
        run: python3 -c 'import build; build.compile_ffmpeg("linux", "x86_64")'
      - name: Build Linux debug x86_64
        run: scons -j4 target=template_debug platform=linux arch=x86_64
      - name: Build Linux release x86_64
        run: scons -j4 target=template_release platform=linux arch=x86_64

      - name: Upload addon
        uses: actions/upload-artifact@v4
        with:
          name: bin_linux_x86_64
          path: test_room/addons/gde_gozen/bin
          retention-days: 5

  build-arm64:
    runs-on: ubuntu-22.04
    steps:
      - name: Installing dependencies
        run: |
          sudo dpkg --add-architecture arm64

          sudo tee /etc/apt/sources.list > /dev/null <<'EOF'
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
          deb [arch=amd64] http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
          
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-backports main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-security main restricted universe multiverse
          EOF

          sudo apt-get update
          sudo apt-get install -y git bash yasm python3 python3-pip scons build-essential diffutils make wget unzip tar ffmpeg binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libaom-dev:arm64

      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compiling FFmpeg arm64
        run: python3 -c 'import build; build.compile_ffmpeg("linux", "arm64")'
      - name: Build Linux debug arm64
        run: scons -j4 target=template_debug platform=linux arch=arm64
      - name: Build Linux release arm64
        run: scons -j4 target=template_release platform=linux arch=arm64

      - name: Uploading Linux bin
        uses: actions/upload-artifact@v4
        with:
          name: bin_linux_arm64
          path: test_room/addons/gde_gozen/bin
          retention-days: 1

