name: 2 | Windows

on: 
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: Addon version
        required: true
        default: test

run-name: Windows build - ${{ inputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Installing dependencies
        run: pacman -Syu --noconfirm sudo fakeroot debugedit patch git bash meson yasm python python-pip scons gcc diffutils make wget unzip tar mingw-w64 ffmpeg wine ninja aom
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install yay
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

          git clone https://aur.archlinux.org/yay.git
          chown -R builder:builder yay

          cd yay
          sudo -u builder makepkg -si --noconfirm
          cd ..

      - name: Install dependency mingw-w64-aom
        run: sudo -u builder yay -S --noconfirm mingw-w64-aom

      - name: Compiling FFmpeg x86
        run: python -c 'import sys; sys.path.append("."); import build; build.compile_ffmpeg_windows("x86_64")'

      - name: Build Windows debug x86_64
        run: scons -j4 target=template_debug platform=windows arch=x86_64
      - name: Build Windows release x86_64
        run: scons -j4 target=template_release platform=windows arch=x86_64

      - name: Uploading Windows bin
        uses: actions/upload-artifact@v4
        with:
          name: bin_windows
          path: test_room/addons/gde_gozen/bin
          retention-days: 1

